namespace FormCraft.ForFluentUI.UnitTests.Components;

/// <summary>
/// Verifies that a form configuration produced by <c>AddFieldsAuto()</c> renders
/// end-to-end with the Fluent UI renderers: strings become text inputs, enums
/// dispatch to the select renderer, booleans become checkboxes, and dates become
/// date pickers.
/// </summary>
public class AutoGeneratedFormRenderingTests : FluentUITestBase
{
    public enum Level
    {
        Bronze,
        Silver,
        Gold
    }

    public class SignupModel
    {
        public string FirstName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string Password { get; set; } = string.Empty;
        public int Age { get; set; }
        public bool AcceptTerms { get; set; }
        public DateTime StartDate { get; set; }
        public Level MembershipLevel { get; set; }
    }

    private IRenderedComponent<FormCraftComponent<SignupModel>> RenderForm(
        SignupModel model, IFormConfiguration<SignupModel> config) =>
        Render<FormCraftComponent<SignupModel>>(parameters => parameters
            .Add(p => p.Model, model)
            .Add(p => p.Configuration, config));

    [Fact]
    public void AutoGenerated_Configuration_Should_Render_All_Field_Types()
    {
        // Arrange
        var model = new SignupModel();
        var config = FormBuilder<SignupModel>.Create()
            .AddFieldsAuto()
            .Build();

        // Act
        var component = RenderForm(model, config);

        // Assert
        component.FindComponents<FluentTextInput>().Count.ShouldBeGreaterThanOrEqualTo(3);
        component.FindComponents<FluentNumberInput<int>>().ShouldNotBeEmpty();
        component.FindComponents<FluentCheckbox>().ShouldNotBeEmpty();
        component.FindComponents<FluentDatePicker<DateTime?>>().ShouldNotBeEmpty();

        // The enum field must dispatch to the select renderer with the enum values
        var select = component.FindComponents<FluentSelect<SelectOption<Level>, Level>>().ShouldHaveSingleItem();
        select.Instance.Label.ShouldBe("Membership Level");
    }

    [Fact]
    public void AutoGenerated_Password_Field_Should_Render_As_Password_Input()
    {
        // Arrange
        var model = new SignupModel();
        var config = FormBuilder<SignupModel>.Create()
            .AddFieldsAuto(options => options.Include(x => x.Password))
            .Build();

        // Act
        var component = RenderForm(model, config);

        // Assert
        var textInput = component.FindComponents<FluentTextInput>().ShouldHaveSingleItem();
        textInput.Instance.TextInputType.ShouldBe(TextInputType.Password);
    }
}
