using FormCraft.ForMudBlazor.Extensions;

namespace FormCraft.ForMudBlazor.UnitTests.Components;

/// <summary>
/// Verifies that a form configuration produced by <c>AddFieldsAuto()</c> renders
/// end-to-end with the MudBlazor renderers: strings become text fields, enums
/// dispatch to the select renderer, booleans become checkboxes, and dates become
/// date pickers.
/// </summary>
public class AutoGeneratedFormRenderingTests : MudBlazorTestBase
{
    public AutoGeneratedFormRenderingTests()
    {
        ((IServiceCollection)Services).AddFormCraftMudBlazor();
    }

    public enum Level
    {
        Bronze,
        Silver,
        Gold
    }

    public class SignupModel
    {
        public string FirstName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string Password { get; set; } = string.Empty;
        public int Age { get; set; }
        public bool AcceptTerms { get; set; }
        public DateTime StartDate { get; set; }
        public Level MembershipLevel { get; set; }
    }

    /// <summary>
    /// Renders the form next to a MudPopoverProvider, which select and picker components require.
    /// </summary>
    private IRenderedComponent<FormCraftComponent<SignupModel>> RenderForm(SignupModel model, IFormConfiguration<SignupModel> config)
    {
        var cut = Render(builder =>
        {
            builder.OpenComponent<MudPopoverProvider>(0);
            builder.CloseComponent();
            builder.OpenComponent<FormCraftComponent<SignupModel>>(1);
            builder.AddComponentParameter(2, "Model", model);
            builder.AddComponentParameter(3, "Configuration", config);
            builder.CloseComponent();
        });

        return cut.FindComponent<FormCraftComponent<SignupModel>>();
    }

    [Fact]
    public void AutoGenerated_Configuration_Should_Render_All_Field_Types()
    {
        // Arrange
        var model = new SignupModel();
        var config = FormBuilder<SignupModel>.Create()
            .AddFieldsAuto()
            .Build();

        // Act
        var component = RenderForm(model, config);

        // Assert
        component.FindComponents<MudTextField<string>>().Count.ShouldBeGreaterThanOrEqualTo(3);
        component.FindComponents<MudNumericField<int>>().ShouldNotBeEmpty();
        component.FindComponents<MudCheckBox<bool>>().ShouldNotBeEmpty();
        component.FindComponents<MudDatePicker>().ShouldNotBeEmpty();

        // The enum field must dispatch to the select renderer with the enum values
        var select = component.FindComponents<MudSelect<Level>>().ShouldHaveSingleItem();
        select.Instance.Label.ShouldBe("Membership Level");
    }

    [Fact]
    public void AutoGenerated_Password_Field_Should_Render_As_Password_Input()
    {
        // Arrange
        var model = new SignupModel();
        var config = FormBuilder<SignupModel>.Create()
            .AddFieldsAuto(options => options.Include(x => x.Password))
            .Build();

        // Act
        var component = Render<FormCraftComponent<SignupModel>>(parameters => parameters
            .Add(p => p.Model, model)
            .Add(p => p.Configuration, config));

        // Assert
        var textField = component.FindComponents<MudTextField<string>>().ShouldHaveSingleItem();
        textField.Instance.InputType.ShouldBe(InputType.Password);
    }
}
